# defaults:
#   - gpt2_LM@model: basic_agent_gpt2_LM
#   - torch_dataset@train_dataset: basic_dataset
#   - torch_dataset@dev_dataset: basic_dataset
#   - evaluator: basic_agent_gpt2_evaluator
#   - _self_


train_dataset:
  data:
    filepath: data/processed_ad/train_filtered.json

dev_dataset:
  data:
    filepath: data/processed_ad/dev_filtered.json


model:
  checkpoint_path: null

evaluator:
  max_generation_len: 512


train:
  save_checkpoint_dir: outputs/basic_agent_test/
  optim_state_path: null
  epochs: 1000
  dataloader_workers: 0
  bsize: 2
  grad_accum_steps: 4
  eval_bsize: 2
  eval_batches: 4
  lr: 1e-4
  weight_decay: 0.01
  max_steps: null
  # loss:
  #   table_head_weight: 0.0
  #   attn_kl_weight: 0.0

wandb:
  use_wandb: true
  wandb_project: train_query_generator
  log_name: null
