BOS_USER_TOKEN = "<bos_user>"
EOS_USER_TOKEN = "<eos_user>"

USER_TOKENS = [BOS_USER_TOKEN, EOS_USER_TOKEN]

BOS_QUERY_TOKEN = "<bos_query>"
EOS_QUERY_TOKEN = "<eos_query>"

QUERY_TOKEN = [BOS_QUERY_TOKEN,EOS_QUERY_TOKEN]

BOS_RETRIEVAL_TOKEN = "<bos_kb>"
EOS_RETRIEVAL_TOKEN = "<eos_kb>"

RETRIVAL_TOKEN = [BOS_RETRIEVAL_TOKEN, EOS_RETRIEVAL_TOKEN]

BOS_RESP_TOKEN = "<bos_resp>"
EOS_RESP_TOKEN = "<eos_resp>"

RESP_TOKENS = [BOS_RESP_TOKEN, EOS_RESP_TOKEN]

SPECIAL_TOKENS = USER_TOKENS + QUERY_TOKEN + RETRIVAL_TOKEN + RESP_TOKENS 